spring:
  profiles:
    active: dev
#  config:
#    activate:
#      on-profile: dev

#  datasource:
#    url: jdbc:mysql://localhost:3306/read_data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
server:
  port: 8000
---
spring:
  profiles: prod

logging:
  level:
    root: DEBUG
---
spring:
  profiles: test

logging:
#  path: /tmp/
#  file: BookWorm.log
  level:
    root: WARN