spring:
#  profiles:
#    active: dev,rcc
  application:
    name: demo-main
#  config:
#    activate:
#      on-profile: dev

#  datasource:
#    url: jdbc:mysql://localhost:3306/read_data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #将ip注册到Eureka Server
logging:
  level:
    root: INFO
server:
  port: 8000
---
spring:
  profiles: prod

logging:
  level:
    root: DEBUG
---
spring:
  profiles: test

logging:
#  path: /tmp/
#  file: BookWorm.log
  level:
    root: WARN