spring:
  application:
    name: demo-ollama
ollama:
  base-url: http://127.0.0.1:11434/v1
  model: deepseek-r1:7b
  api-key: ollama-local
  log-level: info

embedding:
  api-key: ollama-local
  base-url: http://127.0.0.1:11434/v1
  model: deepseek-r1:7b
