spring:
  profiles:
    active: prod

logging:
  level:
    root: INFO
---
spring:
  profiles: dev

logging:
  level:
    root: DEBUG
---
spring:
  profiles: prod

logging:
  path: /tmp/
  file: BookWorm.log
  level:
    root: WARN