spring:
  profiles:
    active: test
  application:
    name: demo-shardingsphere-jdbc-server

server:
  port: 1230
  servlet:
    context-path: /demo-shardingsphere-jdbc-server

pagehelper:
  supportMethodsArguments: true
  reasonable: false
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lp.demo.shardingsphere.jdbc.domain.po

logging:
  config: classpath:logback-spring.xml

