server:
  port: 8088
rcc:
  cc-server-url: http://127.0.0.1:8086/
  project-name: demo
  cc-password: 123456
  env-name: dev
  cc-version-name: 1.0.0
  log-properties: true
  enable-update-callback: true
