server:
  port: 8081

xxl:
  job:
    accessToken: demo-xxljob-token
    admin:
      addresses: ${xxl.job.admin.host}/xxl-job-admin
      host: http://127.0.0.1:8080
    executor:
      address: ''
      appname: demo-xxljob
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999

logging:
  config: classpath:logback.xml
